# Generated by Django 5.1.6 on 2025-02-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=250, unique=True)),
                ('joueurs_min', models.IntegerField()),
                ('joueurs_max', models.IntegerField()),
                ('duree_min', models.IntegerField()),
                ('duree_max', models.IntegerField()),
                ('coop', models.BooleanField()),
            ],
        ),
    ]
