# Generated by Django 5.1.6 on 2025-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0002_alter_jeux_coop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='coop',
            field=models.IntegerField(choices=[(0, 'Non coopératif'), (1, 'Coopératif'), (2, 'En équipe')]),
        ),
    ]
