# Generated by Django 5.1.6 on 2025-03-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0004_jeux_favori_jeux_jamais_joué'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeux',
            name='compétitif',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='jeux',
            name='équipe',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='coop',
            field=models.BooleanField(null=True),
        ),
    ]
