# Generated by Django 5.1.6 on 2025-03-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0005_jeux_compétitif_jeux_équipe_alter_jeux_coop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jeux',
            old_name='compétitif',
            new_name='competitif',
        ),
        migrations.RenameField(
            model_name='jeux',
            old_name='équipe',
            new_name='equipe',
        ),
    ]
