# Generated by Django 5.1.6 on 2025-04-02 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0006_rename_compétitif_jeux_competitif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('duree', models.IntegerField()),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.jeux')),
            ],
        ),
    ]
